### ISSUE TITLE
Best Browser to user this tool

### ISSUE THREAD

**Issue by salarmehr** [monolithpl/fraze-finder#1]
I do appreciate for developing this awesome tool that I was looking for for a while (https://languagelearning.stackexchange.com/questions/2915/any-tool-to-highlight-collocations/2925?noredirect=1#comment3438_2925)

I hope you continue to develop it and my question is is there ant browser bets suit frze-finder? 
Currently, it seems in firefox and Opera the highlight place out of the word in the second half of the text.

**Comment by monolithpl** [comment]
thanks! it's still pretty much a work in progress, i'm currently working on a better list of collocations.
could you send the text that causes problems with the highlighting? i haven't noticed it myself!

**Comment by muranava** [comment]
hi
sorry to contact you here but have you got my emails?
many thanks

**Comment by monolithpl** [comment]
hello!
strangely, no. i didn't get any emails - apart from the first one and the one you sent just now. send it again?
but i think i see what the problem is: when the algorithm finds several expressions that overlap, like:
- body mass
- body mass index
- mass index
it just highlights the last one, erasing the previous highlights. is that what you were pointing out?

**Comment by muranava** [comment]
hi is this email - empikempik@gmail.com working?
thx

**Comment by monolithpl** [comment]
yes it is
